language: node_js
node_js:
  - 10
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - export TZ='Asia/Xiamen'
install:
  - npm install
script:
  - npm run test
after_success:
  - npm run build

jobs:
  include:
    - stage: npm release
      node_js: "10"
      script: npm run build
      deploy:
        provider: npm
        email: "$EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master

